development: &default
  adapter: postgresql
  database: feeder_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 10
  auto_reconnect: true

test:
  <<: *default
  database: feeder_test
